[rocm-libraries] ROCm/rocm-libraries#11657 (commit 45df3ad)
Revert "perf: tune gfx12 fmha d128 bf16 tile size (#11054)"
 (#11657)

This reverts commit 2f22f2282eb7051b3534ea70d7f0862e4129c85e.

## Motivation

CI error on compiling instance:
[2026-09-02T23:44:17.786Z] FAILED: [code=1]
example/ck_tile/01_fmha/CMakeFiles/tile_fmha_fwd_instances.dir/fmha_fwd_d128_fp16_batch_b128x64x64x128x64x128_r8x1x1_r8x1x1_w16x16x16_w16x16x16_o4_qr_hpad_vr_psskddv_nlogits_nbias_nmask_lse_ndropout_nskip_nqscale_ntrload_sink_gfx12.cpp.o

[2026-09-02T23:44:17.786Z]
projects/composablekernel/include/ck_tile/core/container/sequence.hpp:1253:9:
error: static assertion failed due to requirement
'container_reduce(pick_sequence_elements_by_mask(ck_tile::sequence<8, 1,
2, 8>{}, ck_tile::sequence<1, 1, 0, 1>{}), ck_tile::multiplies<void,
void>{}, 1) % 24 == 0': slice size can't evenly divide input sizes

## Technical Details

<!-- Explain the changes along with any relevant GitHub links. -->

## Test Plan

<!-- Explain any relevant testing done to verify this PR. -->

## Test Result

<!-- Briefly summarize test outcomes. -->

## Submission Checklist

- [ ] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.