[rocm-libraries] ROCm/rocm-libraries#9333 (commit 78aa8c7)
feat(ck): Add gfx90c build support

## Motivation

Needed for https://github.com/ROCm/TheRock/issues/3818.

## Technical Details

When building torch w/ TheRock CI (`build_prod_wheels.py`) on gfx90c,
was running into the generic error below compiling
`amd_buffer_addressing_builtins.hpp`
```
  composable_kernel/include/ck/utility/amd_buffer_addressing_builtins.hpp:33:48: error: use of undeclared identifier 'CK_BUFFER_RESOURCE_3RD_DWORD'
  ...:61:22: error: use of undeclared identifier 'CK_BUFFER_RESOURCE_3RD_DWORD'
  ...:73:22: error: use of undeclared identifier 'CK_BUFFER_RESOURCE_3RD_DWORD'
  4 errors generated when compiling for gfx90c.
  ```
 Adding `__gfx90c__` to the arch definition list resolves this.

## Test Plan

Build torch (`build_prod_wheels.py`) for gfx90c before and after patch.

## Test Result

- Before: Fails with `amd_buffer_addressing_builtins.hpp:33:48: error: use of undeclared identifier 'CK_BUFFER_RESOURCE_3RD_DWORD'`

- After: Build passes 

## Submission Checklist

- [ ] Look over the contributing guidelines at https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.